### ISSUE TITLE
[Feature Request] Selection List & Option to turn on Collision for Models

### ISSUE THREAD

**Issue by DaleHat** [mchorse/blockbuster#109]
Selection List
be able to view a list of models and pick them by folder name instead of viewing the models
(reason is i have huge models that dont display properly and i cant really see what im clicking on when selecting a model)

Collision for Models
would be handy to beable to walk on models and not fall threw the floor or walk threw the walls

Better Search Bar
Also to be able to put more words in the search bar

Transparency Setting
maybe a transparency setting aswell so OPs can adjust the transparency of models..

Really liking the mod still especially now that i dont have to remake the same textures multiple times

**Comment by mchorse** [comment]
> be able to view a list of models and pick them by folder name instead of viewing the models
(reason is i have huge models that dont display properly and i cant really see what im clicking on when selecting a model)

That would be very nice indeed. I'm pretty sure I'll add this once I'll have priorities sorted out.

> Collision for Models 
> would be handy to beable to walk on models and not fall threw the floor or walk threw the walls

That's nearly impossible, and even if I'll be able to implement this, it would be most likely incompatible with some mods in a way it wouldn't be usable.

> Better Search Bar
> Also to be able to put more words in the search bar

Please elaborate this one.

> Transparency Setting
> maybe a transparency setting aswell so OPs can adjust the transparency of models..

Model editor already has a slider for individual limb transparencies, but unfortunately due to how MC implements its entity rendering, there might be issue with some stuff missing behind.

> Really liking the mod still especially now that i dont have to remake the same textures multiple times

Thank you! 🙂

**Comment by mchorse** [comment]
> what i mean by Better Search Bar is 'bigger' that fits more characters or has no character limit
> if i try to search up oblivion-architecture-bravil-bravilarcherparadox
> im only able to fit oblivion-architecture-bravil in the search bar

Oh, now I see, I'll add that to my to do list, although it's on Metamorph's side, so I'm not really sure when I'll be working on that.

> and thank you for the fast replys and for the help with my last request about using a directory instead of having duplicates which was already a feature..

No problem. 👍 

> also is it possible to use .dds as textures?
> is there a list i can view all possible texture formats and model formats?

If it didn't work, then it's not possible. IIRC following image formats are supported by ImageIO (which Minecraft uses): jpg, png, gif, wbmp and bmp.

As for model formats, only Blockbuster specific JSON and OBJ (partially).

**Comment by DaleHat** [comment]
okay ty for all the help :D
