### ISSUE TITLE
[Question] Wither skull

### ISSUE THREAD

**Issue by slava110** [mchorse/blockbuster#124]
I don't see wither skull (projectile) in model list. Also tried to use block model and use wither skull block id but doesn't work :c . Is it possible to use wither skulls somehow like flying projectile? Just want to make cool screenshot with them

`blockbuster-1.6.3-1.12.2`
`metamorph-1.1.10-1.12.2`
`forge-14.23.5.2847`

**Comment by mchorse** [comment]
Sadly, wither skull is not a subclass of `EntityLivingBase`, so they cannot be found in the creative morph list... I wanted to implement this feature for a long time, to be able to use `Entity` base entities, but unfortunately, it's quite complicated (it will require me to rewrite lots of code in my mods that use Metamorph as mod dependency).

Maybe one day it will be implemented, but not now... however, you could try exporting wither skull in the model editor (check Options > Controls > Blockbuster for the keybind to open the model editor), and in the models modal (three horizontal lines icon) click on the arrow oriented upwards. If you can find the skull in the list of mobs, try exporting and saving it as a model. That might work, but I can't guarantee it, since the code there is really fragile. 

Good luck!
