### ISSUE TITLE
Beauty issues

### ISSUE THREAD

**Issue by NlL5** [mchorse/blockbuster#14]
Here are some notes I took when testing commit 211ebe09552e7cf17d83732572bf6604566b11b2
I don't know, if they're still up-to-date, though.

**Commands**

- [x] `/morph notexistingmodel` says `You morphed into "notexistingmodel" model.` and morphs you into the default Actor model, even though the model "notexistingmodel" doesn't exist.

**Miscellaneous**
- [x] The description of the Director Block says "Use it for machinimas". I think this is from the old description, because the new Director Block is for adventure maps as well.
- [x] The default Actor model seems to be larger then the normal player. (Tested in Minecraft 1.10.2.) Press F5 and morph into an Actor and back. Also the arms are not idle swinging. But I'm unsure if this is on purpose.

**Comment by mchorse** [comment]
Good job, thanks for reporting! :)

> I don't know, if they're still up-to-date, though.

I think they're still present. 

> The description of the Director Block says "Use it for machinimas". I think this is from the old description, because the new Director Block is for adventure maps as well.

Oops! I forgot to remove that one.

> The default Actor model seems to be larger then the normal player. (Tested in Minecraft 1.10.2.) Press F5 and morph into an Actor and back. Also the arms are not idle swinging. But I'm unsure if this is on purpose.

Hm, that's really weird, because the scale factor of minecraft's `RenderPlayer` is `0.9375F`:

```java
GlStateManager.scale(0.9375F, 0.9375F, 0.9375F);
```

While my actor's scale factor is `0.92F`:

```java
float f = 0.920F;
GlStateManager.scale(f, f, f);
```

Logically it can't be bigger, but should be smaller than player (when demorphed). I should look into that, maybe `alex` and `steve` models aren't completely structured against `ModelPlayer`...

**Comment by NlL5** [comment]
You're welcome ;)
Oh ok :open_mouth: I'm not sure anymore, but it could be that the players legs are 1px smaller..

**Comment by mchorse** [comment]
Maybe perspective makes illusion that player is smaller? Did you tried entering inside actor (merging models) and go to perspective and check the difference?

**Comment by NlL5** [comment]
![2016-10-09_21 37 17](https://cloud.githubusercontent.com/assets/20781376/19223185/04417cf8-8e6a-11e6-84a2-f7e9d0f17d50.png)
You mean like this?

**Comment by NlL5** [comment]
<img src="https://cloud.githubusercontent.com/assets/20781376/19223469/067b3f2a-8e71-11e6-842d-9f590147ce08.png" width="200" style="float:left;">
<img src="https://cloud.githubusercontent.com/assets/20781376/19223470/086954ac-8e71-11e6-8300-d80b2990a0a0.png" width="200" style="float:left;">

**Comment by mchorse** [comment]
Hm, very peculiar... Thanks for screenshot, I shall investigate further :male_detective: :mag_right:

**Comment by mchorse** [comment]
I just realized what is the problem with actor's sizes. The scale factor `0.920F` doesn't work, because it doesn't gets invoked, and it doesn't gets invoked because I copy pasted this method from RenderPlayer who has different class inheritance... whoops 😆 

So the problem is found, and I'll fix it ASAP.

**Comment by NlL5** [comment]
ahhh ok xD

**Comment by mchorse** [comment]
All these things have been fixed, thanks for reporting! :)

**Comment by NlL5** [comment]
Cool! :smile: You're welcome ;)
