### ISSUE TITLE
Hi, I've come into a bit of a knot. So everytime I go into the models folder in Blockbuster, and drop a custom skin into the Steve or Fred folders, nothing shows up! I've tried putting the skins in other folders, redownloading the mod, and even restarting my computer. But it always happens! Please help! 

### ISSUE THREAD

**Issue by WickedLemonFists** [mchorse/blockbuster#190]

**Comment by hedw1gP** [comment]
Would you mind showing your `.minecraft/config/blockbuster/` structure?

**Comment by WickedLemonFists** [comment]
https://i.imgur.com/9Jy0Qvu.png
https://i.imgur.com/qUe4T3B.png

**Comment by mchorse** [comment]
> https://i.imgur.com/9Jy0Qvu.png
> https://i.imgur.com/qUe4T3B.png

In order to pick a skin, with this setup, you need to select `blockbuster.fred` morph in the morph menu, press Q, and then in the list pick the skin. For more information, take a look at [this video](https://www.youtube.com/watch?v=33S4PFVuygc).

Also, thanks @hedw1gP for prompting WickedLemonFists for showing the structure. 😊

**Comment by WickedLemonFists** [comment]
Thank you both so much! All I had to do was press Q! I appreciate your help!
