### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Renario910** [mchorse/blockbuster#22]
if you are in survival, zombie emits a burning sound, but doesnt butn itseld (doesnt deal damage). Also i cant open the menu using N so i cant make some mobs favorite. ALso also make so you can remove existing mobs and also search

**Comment by kyle81576** [comment]
Same issue with the zombie, seems that when you morph from the creative menu and switch to survival you retain the abilities, where as when you morph using the survival menu you morph shape but no abilities come with it. The squid drowned and was still fairly slow from the survival menu.

**Comment by ShadesRaith** [comment]
1.11.2 has no abilities for any mobs active or passive

**Comment by mchorse** [comment]
*Ahem*, guys! 😄 

As you can see this is actually Blockbuster's issue tracker, not Metamorph's. To be honest, I'm not really sure whether I can fix this bug, since this code is running in vanilla, and I don't have access to it. I'll look into that, however, and see if I can fix this.

Also, if you experience lack of abilities and actions, then try updating to Metamorph `1.1.2`. There was a bug in initial build of `1.1` for `1.11.2`, so an update should fix this.

@kyle81576 yeah, I'm acknowledged of this bug, and I already fixed this, but at the moment the bug fix is stashed in the code along with `1.4.8`, which is unpublished and you can already download it, see this [reddit post](https://www.reddit.com/r/mcpub/comments/62ykfj/blockbuster_148_preview_builds/).
