### ISSUE TITLE
Blockbuster mod crashes

### ISSUE THREAD

**Issue by kampty** [mchorse/blockbuster#222]

**Comment by kampty** [comment]
Hello. Blockbuster mod crashes
I attached error log
[crash.txt](https://github.com/mchorse/blockbuster/files/8694596/crash.txt)

**Comment by kampty** [comment]
@mchorse

**Comment by kampty** [comment]
@Chryfi

**Comment by Chryfi** [comment]
I cant really see a blockbuster error in the crash log... Also you have like 30 other mods... Did you try removing them to test out which one is the crash reason?

**Comment by mchorse** [comment]
> Hello. Blockbuster mod crashes
> I attached error log
> [crash.txt](https://github.com/mchorse/blockbuster/files/8694596/crash.txt)

First of all, there is no point in pinging since I get notification anyway. 

This crash has nothing to do with Blockbuster mod as Chryfi stated. Judging from the log, the most possible cause of the crash is due to RenderPlayerAPI mod IMO. Try disabling this mod and its dependents and see if it fixes the crash. If not, then it’s one of the mods that has a core mod (see the list on the top).

**Comment by kampty** [comment]
> > Hello. Blockbuster mod crashes
> > I attached error log
> > [crash.txt](https://github.com/mchorse/blockbuster/files/8694596/crash.txt)
> 
> First of all, there is no point in pinging since I get notification anyway.
> 
> This crash has nothing to do with Blockbuster mod as Chryfi stated. Judging from the log, the most possible cause of the crash is due to RenderPlayerAPI mod IMO. Try disabling this mod and its dependents and see if it fixes the crash. If not, then it’s one of the mods that has a core mod (see the list on the top).

Thank you very much! It helped
