### ISSUE TITLE
If I want to help translate this mod

### ISSUE THREAD

**Issue by ycwei982** [mchorse/blockbuster#25]
Where I can start to do? It's difficult for me to find a string file or I just be too lazy lol.

**Comment by mchorse** [comment]
Hey! I'm really appreciate your willing to make this mod available to other language :)

To be honest, the process of translation is a bit complex than for other mods, because of all formatting, and **a big volume of strings**. All strings are located in repository's folder `help/en_US/` in files with file extension `.yml`. To start translating simply 

* Create a folder with localization name, (like `fr_FR`) in `help` folder
* Copy all `.yml` files in `help/en_US/` to your language folder (for this example with French, `help/fr_FR/` 
* And start translating! :slightly_smiling_face: 

To see the effect of your translation in the game, you'll need to follow instruction in the file `README.md` in the last section. You'll need to install composer and initiate script dependencies.

Let me know if you will have any questions!

**Comment by ycwei982** [comment]
Alright thanks! I'm working on it now =) and I would like to distribute this to a non-English forum with your credit, if there is enough time I will also make an introduction video, is there anything need to add in else?

**Comment by mchorse** [comment]
Distribute you mean like in as non official build? I mean like, without pull requesting this translation to the *official* build? I think that for such big mod, an introduction video is required. There are too many fearures that might be shown, because the mod isn't intuitive enough. It would very helpful if you could make a little tutorial like my 'How to create Minecraft machinima with Blockbuster'.

**Comment by mchorse** [comment]
Whoops, wrong button :joy:

**Comment by ycwei982** [comment]
I don't mean that "distribute"... Maybe you can understand as "share" or "repost" or stuff like that...

**Comment by mchorse** [comment]
Yeah, sharing/reposting is totally cool, could you also add a link to my YouTube channel when you'll be reposting? That would be very appreciated! :slight_smile:

**Comment by ycwei982** [comment]
Of course I will (although China mainland can't access YouTube...), but I will record a tutorial in Chinese similar to your YouTube content.

**Comment by mchorse** [comment]
@ycwei982 oh, wait, I forgot one thing to do, the config comments are impossible to translate at the moment, so I'll have to write some code to make it possible. I'll let you know when I'll finish.

**Comment by ycwei982** [comment]
I will wait :D maybe when you finished I will clone a brand new repository and copy my existing files lol
