### ISSUE TITLE
Mo'Bends Glitch

### ISSUE THREAD

**Issue by Proman101010** [mchorse/blockbuster#31]
Add support for Mo'bends if possible. if not, i should report this to Mo'Bends.

**Comment by mchorse** [comment]
Could you explain me what exactly happens when is installed Metamorph along side with Mo' Bends?  can't fix if there's no any clue of what's going on.

**Comment by ycwei982** [comment]
It is not Blockbuster’s issue, it has to do with Metamorph.

**Comment by mchorse** [comment]
By the way, I've been testing Metamorph with Mo' Bends (and also reading its code), and I can say that it's impossible to make Mo' Bends to work with Metamorph due to the way how it's working. In order to make Mo' Bends to work with Metamorph, it will require the entities to be actuallly spawned in the world to be animated, so... it will only cause even more problems.

Meanwhile I wrote a PM to GoblinBob on CF, and he still haven't replied

**Comment by mchorse** [comment]
Can't fix that...
