### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by Puppylove2492** [mchorse/blockbuster#52]
So I added my skins to my server file for blockbuster now it won't show up for others why?

**Comment by mchorse** [comment]
*Wait, how did it get here? I never seen this issue before and it says it was opened 18 days ago... I'm confused...*

Anyways 😁 Blockbuster isn't very good with multiplayer resources (models/skins) compatibility, so in order to show skins to other people, you have to send those skins to those people by yourself. 

There are few disclaimers in the wiki about multiplayer and server support, so go check that, but I plan in the future to resolve that issue.
