### ISSUE TITLE
Facial animations with Blockbuster?

### ISSUE THREAD

**Issue by TheSexyYeti** [mchorse/blockbuster#88]
I don't know if you can do this or not. Or weather you already have this in your mod. I just downloaded it and haven't yet had a chance to mess with it yet. But is there a way to add facial animations to the models. I was thinking about it. If let's say I make my own skin. 

But within the texture I also add different variations of the front of the face with different mouth, eye and eye brow movements. And then within Blockbuster's GUI I can switch the textures of the front of the face with what ever facial movement I need for the scene. Allowing for dialog with actual articulated mouth movements and such. With Minecraft's low resolution skins you might not be able to do much of a facial animation and it be noticeable. There is a way to get HD skins using the More Player Models mod. 

But I don't think that would work since the only way to do it is to use the More Player Models mod to load a skin from a URL. Unless you integrate a way to use HD skins in your mod. Anyways I know I'm babbling. I just thought this was a good suggestion.

**Comment by mchorse** [comment]
Hello, everything you suggested in this post is possible with Blockbuster, however requires some work. There are several ways of make it work. You can make facial expression work in few different ways:

1. High resolution skins. **Pros**: easy to edit, just add stuff to the skin and done. **Cons**: it's rather difficult if you have many variation of skins you want to use it for, and also very stressful on RAM/GPU.
2. Body part system with image morphs. With morph editor, you can add models inside of models, so this way you can add clip art of eyes and mouth separately on top of the character. **Pros**: very modular, you can change the skin of the character, without messing up the eyes and mouth. **Cons**: longer to setup, requires decent knowledge of Blockbuster and could clutter up morph management.

For 2., I would suggest you to watch [1.5.3](https://www.youtube.com/watch?v=sWlh0LUvvMc) and [1.6](https://www.youtube.com/watch?v=wpfiLTrzTLs) change log videos. Also, HD skins are supported by default due to how UV mapping works.

I'm going to close this issue since I think I should've provide with enough of information to get started, however, if you want to continue discussion, I would rather recommend you to hop on [my Discord server](https://discord.gg/qfxrqUF), as it would be easy for me.

I hope you found it helpful. 👍
