### ISSUE TITLE
Record Start Crash

### ISSUE THREAD

**Issue by jimizpro** [mchorse/blockbuster#97]
https://pastebin.com/Ej3SEjv7

so my minecraft crashes whenever the record starts

blockbuster 1.6 - 1.12.2

**Comment by mchorse** [comment]
That happens when the picked morph in director block menu is empty (light blue chicken). This bug was fixed in 1.6.1, but it didn't come out yet. Feel free to use [this one](https://cdn.discordapp.com/attachments/548439751682687016/602779924255997953/blockbuster-1.6.1-1.12.2-dev3.jar) (I see you have it, but it requires McLib 1.0.3, keep that in mind).

**Comment by jimizpro** [comment]
> That happens when the picked morph in director block menu is empty (light blue chicken). This bug was fixed in 1.6.1, but it didn't come out yet. Feel free to use [this one](https://cdn.discordapp.com/attachments/548439751682687016/602779924255997953/blockbuster-1.6.1-1.12.2-dev3.jar) (I see you have it, but it requires McLib 1.0.3, keep that in mind).

Yeah I just saw the other post before you replied Haha
